### ISSUE TITLE
integrationTest task not added but integrationTestJar and integrationTestClasses

### ISSUE THREAD

**Issue by drjasonharrison** [unbroken-dome/gradle-testsets-plugin#26] opened 2017-01-16 20:36 UTC
I'm trying to follow the README.md instructions, but gradle does not recognize the integrationTest task. I do get an integrationTestJar and an integrationTestClasses task.

gradle -v
------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------

Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Mac OS X 10.11.6 x86_64

I tried using the example from [https://github.com/pkainulainen/gradle-examples](https://github.com/pkainulainen/gradle-examples). 

I've also tried using gradle 3.0, 2.14 and 2.9

Which version of gradle is this known to work with?

**Comment by tkrullmann** [comment] 2017-01-16 21:26
Hi @drjasonharrison, I can't reproduce this with the example from the linked repo. Tried with several versions of the plugin and of Gradle. Could you attach a build.gradle file for which this occurs?

**Comment by tkrullmann** [comment] 2017-01-16 21:51
Possible duplicate of #23?

**Comment by drjasonharrison** [comment] 2017-01-16 22:04
I do see under "Other tasks" integrationTest, so yes, possible duplicate of #23.

**Comment by drjasonharrison** [comment] 2017-01-16 22:15
version 1.3.2 now has integrationTests under "Verification tasks" 
Thanks again!

**Closed as completed** 2017-01-16 22:18 UTC
Labels: duplicate
