### ISSUE TITLE
Warning deprecation in Gradle 5.4.1

### ISSUE THREAD

**Issue by yuriy-slobodchikov** [unbroken-dome/gradle-testsets-plugin#76] opened 2019-06-24 19:42 UTC
Warning deprecation in Gradle 5.4.1
...
line 73    apply plugin: 'org.unbroken-dome.test-sets'
...
line 89 testSets {
line 90     integrationTest {
            dirName = "integrationTest"
        }
    }
...

gradle --warning-mode all

> Configure project :
Internal API constructor DefaultPolymorphicDomainObjectContainer(Class<T>, Instantiator) has been deprecated. This is scheduled to be removed in Gradle 6.0.
        at build_6osb3c58wjj2abijvlueeo14t$_run_closure1.doCall(...\build.gradle:73)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The ProjectLayout.configurableFiles() method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the ObjectFactory.fileCollection() method instead.
        at build_6osb3c58wjj2abijvlueeo14t$_run_closure1$_closure6.doCall(...\build.gradle:90)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

**Comment by tkrullmann** [comment] 2019-07-07 07:20
Hi,
unfortunately this is something I can't easily fix without breaking compatibility with earlier Gradle versions.
The Gradle API still doesn't contain an "official" way to construct a `PolymorphicDomainObjectContainer`, and the said constructor is the only one that already existed in 4.10.

**Comment by tkrullmann** [comment] 2019-07-07 07:21
Duplicate of #63

**Closed as completed by tkrullmann** 2019-07-07 07:21 UTC
Labels: duplicate
